package com.mastek.domain;

public enum DecisionEventEnum {
	    NOACTION,TIMESPENT, TIMESPENTONAMT,  NAMECHANGEAFTEREMAIL,
	    TOOMANYNAMECHANGES,PASSPORTDTLPROVIDED,PREMIUMDEVICE, COMMIT, DEVICEUSED
}
